### ISSUE TITLE
Armor still equipable

### ISSUE THREAD

**Issue by Thyriel** [Darkhax-Minecraft/ItemStages#1]
As long as you don't take it in your hand armors that are behind a stage can still be equiped.

**Comment by darkhax** [comment]
Thanks for reporting. There are a few situations where you can bypass this, like the offhand slot, and wearing the armor before having the stage removed. I will have fixes for this and more out very soon.

**Comment by darkhax** [comment]
Closed in https://github.com/Darkhax-Minecraft/ItemStages/commit/1a5ebdd32f3baf23962aa1e5698cb438d4186e37
