### ISSUE TITLE
[Suggestion] AddItemStageByMod

### ISSUE THREAD

**Issue by EmosewaPixel** [Darkhax-Minecraft/ItemStages#11]
It's self-explanatory. I suggest adding a way of restricting all items from a certain mod, if it's possible.

**Comment by Matryoshika** [comment]
You can do this easily enough with a for-loop using CraftTweaker's loadedMods lookup.

> for item in loadedMods["thermalexpansion"].items {
>      mods.ItemStages.addItemStage("electrical", item);
> }

Yes, it's not a simple one-liner, but it is functionally exactly the same.

**Comment by darkhax** [comment]
I have been considering this feature for a while. You can use loops like the one described above to easily stage an entire mod, and this has been the preferred way to do this for many modpack authors because it allows for more optimization. I will add the requested feature either way.

**Comment by Lanse505** [comment]
I highly second this x)
For loops are fine and all, but yea nope, I'd prefer not having a few million lines of output prints for each base item + meta/nbt variations :P

**Comment by darkhax** [comment]
This feature is included in [1.0.28](https://minecraft.curseforge.com/projects/item-stages/files/2537878)

```
mods.ItemStages.stageModItems("one", "minecraft");
```
