### ISSUE TITLE
Problems on my server while trying to make a modpack.

### ISSUE THREAD

**Issue by Mortismorte** [Darkhax-Minecraft/ItemStages#12]
I'm making a modpack using itemstages 1.12.2 1.0.28, in single player it works fine (after I turn off creative mode) but on the server all that works right is the hiding in jei.

**Comment by darkhax** [comment]
Does the server also have CraftTweaker, GameStages, ItemStages, and all the scripts?

**Comment by Mortismorte** [comment]
yes it does

**Comment by Mortismorte** [comment]
I double checked, and yes they are all there.

**Comment by Mortismorte** [comment]
would dimension stages or recipe stages cause any conflicts?

**Comment by darkhax** [comment]
No, they would not cause conflict.

**Comment by Mortismorte** [comment]
I do start in creative, then leave creative, then set me to have the stage then deop myself.
then try the items. I've tried throwing them to another person helping me, also not in creative or opped. and he was able to hold/place the items.

**Comment by Mortismorte** [comment]
erm not have the stage sorry

**Comment by Mortismorte** [comment]
Could the problem be I'm using forge version 14.23.2.2624

Also not sure if this has anything to do with it but I get this in the console when someone joins the server:
[01:49:54] [Netty Epoll Server IO #1/INFO] [journeymap]: CLIENT
[01:50:16] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[01:50:16] [Server thread/INFO]: Tried to load unrecognized recipe: crafttweaker:ct_shaped-2097842201 removed now.
edit: 7 more with differnent ending numbers then ->
[01:50:16] [Server thread/INFO]: Mortismorte[/edited] logged in with entity id 222 at (-199.59157847971656, 63.0, -6017.0490594527155)
[01:50:16] [Server thread/INFO]: Mortismorte joined the game

**Comment by Mortismorte** [comment]
Trying something now, took a long look at craft tweaker's log and found that I may have had a punctuation error. Hope this fixes it.

**Comment by Mortismorte** [comment]
Ok I found right away using:
minecraft 1.12.2 
forge 14.23.2.2624

With mods:
Bookshelf-1.12.2-2.3.533
CraftTweaker2-1.12-4.1.6
GameStages-1.12.2-1.0.80
ItemStages-1.12.2-1.0.28

and it still is letting normal survival players (not even mentioned in ops.json) hold and place restricted items. It does rename them to restricted and give all that info, but they can hold/place and presumably wear restricted items as if they were not.

**Comment by darkhax** [comment]
Can you please upload the craftweaker.log file from the server?

**Comment by Mortismorte** [comment]
[crafttweaker.log](https://github.com/Darkhax-Minecraft/ItemStages/files/1809643/crafttweaker.log)

Here is the log from the test server with just the 4 mods

**Comment by darkhax** [comment]
Thanks. So based on this script stone is the only staged item?

**Comment by Mortismorte** [comment]
yes - as i was going to test adding mods to see if there was a bad interaction, took out mod tweaker, and dimension and recipe stages when I couldn't get it to work with just those in it. Then same thing.

**Comment by Mortismorte** [comment]
also if necessary I can let you try on the test server or give you sub admin to it (i use akliz) so you can better see what's happening on the non programming end

**Comment by darkhax** [comment]
Sorry for taking so long to fix this issue, it was such a silly mistake on my part and none of the people I asked were using this version. I have tested this on a local server I set up and it should completely solve the issue. Please let me know how it goes. You can get the patched version [here](https://maven.mcmoddev.com/net/darkhax/itemstages/ItemStages-1.12.2/1.0.29/ItemStages-1.12.2-1.0.29.jar)

**Comment by Mortismorte** [comment]
No worries, it happens to all of us, specially if you've been working or coding all day and finally go to fix an issue but are tired etc.....

Works just fine on the small testing server.

And is now partially working in my modpack developement server.

Not sure if it is because of the item types of the items involved, one places like a block the other gets placed inside of the first. 

Not sure how familiar you are with sky resources 2?

The frames and tools get chucked while, the combustion heater, condenser and dirty gems do not
this may need to go under a seperate issue as it's prolly they way the added in the items?
