### ISSUE TITLE
Config suggestions

### ISSUE THREAD

**Issue by DevTimur** [Darkhax-Minecraft/ItemStages#13]
Make "Hidden in JEI" and "Renamed to Restricted Item" options configurable.

Because i WANT to see this item in JEI, and i want to see it's recipe. Just a small hint saying "You need *this* stage to use it"

**Comment by DevTimur** [comment]
Oh, sorry, you already implemented it. I need to download newer version.
*DERP*

**Comment by darkhax** [comment]
I don't believe renaming is configurable, so I can add that.

**Comment by darkhax** [comment]
The second feature you requested has been added. A new build will show up on Curse shortly.
