### ISSUE TITLE
Server JEI Item Hiding Syncing Issue

### ISSUE THREAD

**Issue by artdude543** [Darkhax-Minecraft/ItemStages#15]
It seems the syncing for hiding items is broken on servers; loading into a single player world all the items which you don't have access to are hidden. But on the server, JEI shows more pages that the player even has access too.

In 3.0.1 of SevTech: Ages this was not an issue. But with the newest update, it's now an issue. Could be related #14 but I don't think so.

**Comment by Buuz135** [comment]
That was my fault! Sorry!

**Comment by darkhax** [comment]
🗡
