### ISSUE TITLE
Hidden Ores Have Inherited Mining Levels / Hardness Again

### ISSUE THREAD

**Issue by Darkosto** [Darkhax-Minecraft/ItemStages#16]
Mining hidden blocks/ores have lost the hardness of the block they are being hidden as and are inheriting what the hidden block is set to.

**Comment by darkhax** [comment]
After testing this out in my dev environment, the issue can not be reproduced with what you have given me in a dev environment. I am guessing that an interaction with another mod is causing this.

**Comment by darkhax** [comment]
Thencecron is saying this issue is no longer valid.
