### ISSUE TITLE
Broken JEI hiding when restricting items with stageModItems

### ISSUE THREAD

**Issue by EmosewaPixel** [Darkhax-Minecraft/ItemStages#17]
Items restricted with stageModItems are restricted (have the tooltip and can't be held), but are still in JEI
![image](https://user-images.githubusercontent.com/25333164/38263268-f63a7a0a-376f-11e8-90db-743c9b77c85e.png)

To clarify, Ender IO was just used as an example. It's the same for the 70 other mods' items I have restricted like this.

**Comment by TheNimbleNinja** [comment]
bump

**Comment by darkhax** [comment]
The lookup code has been improved and will now catch all the enchantment books from the edge case I mentioned in my response. Fluids are still not supported at this time. https://github.com/Darkhax-Minecraft/Bookshelf/commit/4aa96f3ef59eeeb29892b1bc372ea0790cf41702
