### ISSUE TITLE
Add ability to hide Mekanism Gasses

### ISSUE THREAD

**Issue by justinrusso** [Darkhax-Minecraft/ItemStages#18]
Since its been a while, I wanted to make an issue *just in case* 👍

**Comment by darkhax** [comment]
Funny story, I actually added this feature on the 5th of march, but forgot about it. https://github.com/Darkhax-Minecraft/ItemStages/commit/0cdd7b5f6d18d98e823d8149f3ea5eb919e6f0a0 

Info on how to use it has been added tot he docs.
