### ISSUE TITLE
Inventory check should run later during login.

### ISSUE THREAD

**Issue by tahg** [Darkhax-Minecraft/ItemStages#19]
When logging into a server, if you're holding an item that requires a stage, it is dropped.  This seems to be because the check happens before Game Stages has loaded its stage data for the player.

**Comment by darkhax** [comment]
This should be fixed in the 2.0 rewrites. Still waiting on more testing and confirmation before that is used in SevTech though.

**Comment by darkhax** [comment]
This has been fixed in the 2.0 rewrite.
