### ISSUE TITLE
Feature Request: Hide all items until staged

### ISSUE THREAD

**Issue by power-spike** [Darkhax-Minecraft/ItemStages#22]
Greetings, 

have read around, and haven't found a way to do this easily without a ton of scripts. 

it is possible to have a configuration option, to Hide all items/recipes until staged?

basically, nothing shows up (In JEI) until you add it to a stage (and the stage is unlocked). 

Add additional option this this, would be "automatically set player to stage". This would allow a player to be added to a stage on first world join.

**Comment by DevTimur** [comment]
I think "automatically set player to stage" equal not using stage in first place.

Also you can hide all items from certain MOD
```
// Locks all items from a mod to a stage
mods.ItemStages.stageModItems("one", "minecraft");
```

**Comment by darkhax** [comment]
I don't really see how this feature would be helpful. I have worked with a lot of pack devs, and it seems that they all use this as a way of tracking what is left to stage. With that said, you could write some very simple script to stage all the items to a default stage, and then stage them again afterwards to change them. 

For example, you can use `for mod in loadedMods` to loop through the loaded mods, and then `mods.ItemStages.stageModItems("default", modname);` to stage everything in that mod. Normally I don't mind adding features that I don't understand the usefulness of, however in this case it is very simple to do what you want with the existing tools.
