### ISSUE TITLE
Applying a gamestage to Blood Magic items permanently removes the recipes from JEI

### ISSUE THREAD

**Issue by AranaiRa** [Darkhax-Minecraft/ItemStages#23]
Even after gaining the appropriate game stage, you cannot check items in JEI anymore until the game is restarted. This affects any blood magic specific crafting (alchemy array, blood altar, alchemy table), but crafting table recipes still display fine.

**Comment by darkhax** [comment]
This sounds like a JEI issue or a blood magic issue to me. JEI is probably seeing those recipe categories as having 0 recipes, and deleted them to remove clutter. But then never re-adds them.

**Comment by AranaiRa** [comment]
Discovered that JEI entries return once the client has been restarted after the stage is added. Closing issue.
