### ISSUE TITLE
Request: Status effect task

### ISSUE THREAD

**Issue by AranaiRa** [Darkhax-Minecraft/ItemStages#24]
I'd like to see a task for being affected by a specific potion effect (maybe with parameters for duration under effect). It'd help for the quest book I'm writing currently.

**Comment by AranaiRa** [comment]
Well I intended this to be posted in Better Questing, but I somehow posted it here. I apologize for the madness.

Though actually being able to stage status effects could be helpful!

**Comment by darkhax** [comment]
Being able to stage status effects would be cool, I will add it to my list of mods I plan to make. Although that's not really for this issue tracker so I will close this for now.
