### ISSUE TITLE
To save time

### ISSUE THREAD

**Issue by lobbienjonsji** [Darkhax-Minecraft/ItemStages#25]
mods.ItemStages.stageAllItemsExcept (stage, [items not to be staged]) and mods.ItemStages.stageModItemsExcept (stage, mod, [items not to be staged]) would be a nice addition to save time and make the scripts smaller.

**Comment by darkhax** [comment]
It is already possible to recreate this with basic CrT. I may add this in the future, however I kind of want to keep things lightweight for now, and encourage people to learn CrT Zenscript instead.
