### ISSUE TITLE
Unable to break or interact with blocks while holding a staged item.

### ISSUE THREAD

**Issue by SuperKael** [Darkhax-Minecraft/ItemStages#26]
While holding any staged item, whether or not the corresponding stage is unlocked, I am unable to break blocks, or interact with blocks (such as opening and closing doors). I am able to break blocks that break instantly, such as grass, but when I do no sound is played. When trying to break other blocks, simply no progress gets made, no cracks appear. When trying to interact with a block, it appears to work, but then it quickly reverts, such as a door re-closing itself. I am playing on a dedicated server - that is probably related.

I am using CraftTweaker2 4.1.9, GameStages 2.0.91, and ItemStages 2.0.35.

And before you ask, yes I have confirmed the CraftTweaker scripts are the same on both the client and server.

EDIT: Oh and using the items themselves works just fine, such as eating food. It's just interacting with the world that has issues.

EDIT 2: Unsurprisingly, after changing the config to allow interaction with restricted items, it now works fine. However, since the problem is with items that have been un-restricted, this is clearly an issue, and the config change is merely a workaround.

**Comment by darkhax** [comment]
Hey there, I actually fixed this issue a few hours before you reported it. Try using GameStages 2.0.98 and ItemStages 2.0.36. If you still have the issue after that, please let me know and I can re-open this.

**Comment by SuperKael** [comment]
I can confirm that the latest version fixes this. Thank you, and sorry for the trouble!
