### ISSUE TITLE
Renamed items aren't properly hidden in JEI

### ISSUE THREAD

**Issue by hgsbsn** [Darkhax-Minecraft/ItemStages#27]
Examples of this include Actually Additions' block inputter, which has a changing name, and Opencomputers' cards, which have an italic name as a vanilla renamed item would. It looks like sometimes they don't have the stage applied at all and sometimes they just don't load correctly. In these screenshots, the entire mod is staged. My scripts include staging for these items:

<opencomputers:storage:1>,
<opencomputers:storage:*>,

<actuallyadditions:block_inputter>,
<actuallyadditions:block_inputter_advanced>,
![2018-08-11_03 47 28](https://user-images.githubusercontent.com/25373556/43991059-957c1484-9d19-11e8-971a-e4bc137b3736.png)
![2018-08-11_03 47 37](https://user-images.githubusercontent.com/25373556/43991060-959ae9ea-9d19-11e8-8b27-786596a47fab.png)

**Comment by darkhax** [comment]
There were a few client/server desync issues, and lookup improvements that have been made since you opened this issue. Could you please try again using the latest versions of Bookshelf, GameStages, and ItemStages? If the issue still happens, can you paste some script examples?
