### ISSUE TITLE
Non-NBT version of item being staged as well as the NBT specified item

### ISSUE THREAD

**Issue by justinrusso** [Darkhax-Minecraft/ItemStages#3]
I'm trying to stage the normal bucket in stage one, and 2 buckets filled with something in stage 3. The end result is that the empty bucket is staged in 3, as is the NBT ones (with fluids)

It does show in JEI when stage one is unlocked, but the item is still restricted, and the tooltip states that stage three is required. Unlocking stage three then un-restricts it. (which is common interaction when an item has multiple stages assigned from my experience)

Script:
```Apache
mods.ItemStages.addItemStage("one", <ceramics:clay_bucket>);
mods.ItemStages.addItemStage("three", <ceramics:clay_bucket>.withTag({fluids: {FluidName: "redstone", Amount: 1000}}));
mods.ItemStages.addItemStage("three", <ceramics:clay_bucket>.withTag({fluids: {FluidName: "redstone_alloy", Amount: 1000}}));
```

**Comment by justinrusso** [comment]
Thank you!

Its fixed the issue for the most part, but now the one with no nbt tag does not get staged at all.

**Comment by darkhax** [comment]
Are you staging the one with no tags specifically?

**Comment by justinrusso** [comment]
Yes. <ceramics:clay_bucket>

On Jan 5, 2018, 2:10 AM -0500, Tyler Hancock <notifications@github.com>, wrote:

Are you staging the one with no tags specifically?

**Comment by justinrusso** [comment]
My fault - script was erroring. All good now! 👍
