### ISSUE TITLE
stageModItems does not work correctly for items with Tags

### ISSUE THREAD

**Issue by clubpetey** [Darkhax-Minecraft/ItemStages#31]
Using AgriCraft as an example...

Executing mods.ItemStages.stageModItems("one", "agricraft") does correctly stage the basic Wooden Irrigation Channel with recipe name
`<agricraft:water_channel_normal>`

But does not stage the variants of the tunnel with different wood types.  Such as
`<agricraft:water_channel_normal>.withTag({agri_material_meta: 8, agri_material: "chisel:planks-spruce"})`

the difference seems to be the ones that aren't staged have ".WithTag()"

**Comment by darkhax** [comment]
You can use :* to stage all of the sub variants of an item. You can also stage things with partial NBT instead of using the exact nbt.

**Comment by clubpetey** [comment]
That works for items, but I'm trying to stage all the items for a mod with stageModItems.  Are you suggesting:
`mods.ItemStages.stageModItems("one", "agricraft:*")`

**Comment by darkhax** [comment]
If you want to stage everything in a mod, there is another function for that. `mods.ItemStages.stageModItems("one", "agricraft");`

**Comment by clubpetey** [comment]
Yes, and that is what I made my original post about.  stageModItems does not stage everything.  It does not stage items with tags.
