### ISSUE TITLE
Language file and locked item name

### ISSUE THREAD

**Issue by CaiganMythFang** [Darkhax-Minecraft/ItemStages#32]
In the en_US.lang file, there is 

> tooltip.itemstages.name.default=Unfamiliar Item

But changing it (via resource loader/resource pack overriding) does not change the name of locked items within the game. Changing the other lines for the tooltips, however, do change them in game.

Is there a way to change the default name of locked items, or be able to in an update?

**Comment by darkhax** [comment]
This tooltip key is no longer used by the mod. You can use setUnfamilarName to set a specific locked name for a specific item. I will look into making this changeable in a future update.

**Comment by CaiganMythFang** [comment]
Thank you! Question, how is the script format laid out for that? I'm doing : 

> mods.ItemStages.setUnfamiliarName("Locked Item", <minecraft:gravel>);

As a test and it renames it back to gravel instead of Locked Item.

**Comment by darkhax** [comment]
It should be `mods.ItemStages.setUnfamiliarName("Locked Item", <minecraft:gravel>);`
