### ISSUE TITLE
Not working for hiding whole mods

### ISSUE THREAD

**Issue by TheQuantumGeneral** [Darkhax-Minecraft/ItemStages#33]
I get this error and none of the mods get hidden

ERROR: [crafttweaker]: Error executing {[0:crafttweaker]:Quaesitum_Stages_Mods.zs}: null

only an issue with this script; ive been able to stage ores and things without issue

/*   
    Staging for mods
*/

import mods.ItemStages.stageModItems;

//Stage 1
stageModItems("stage1", "quark");
stageModItems("stage1", "akashictome");
stageModItems("stage1", "architecturecraft");
stageModItems("stage1", "charset");
stageModItems("stage1", "thermalfoundation");
stageModItems("stage1", "betterwithmods");
stageModItems("stage1", "betterwithlib");
stageModItems("stage1", "chisel");
stageModItems("stage1", "chiselsandbits");
stageModItems("stage1", "cookingforblockheads");
stageModItems("stage1", "rustic");
stageModItems("stage1", "exchangers");
stageModItems("stage1", "forgemultipartcbe");
stageModItems("stage1", "microblockcbe");
stageModItems("stage1", "minecraftmultipartcbe");
stageModItems("stage1", "jaopca");
stageModItems("stage1", "mcmultipart");
stageModItems("stage1", "forge");

//Stage 2
stageModItems("stage2", "ironchest");
stageModItems("stage2", "funkylocomotion");
stageModItems("stage2", "drawbridges");
stageModItems("stage2", "buildinggadgets");
stageModItems("stage2", "buildcraftcompat");
stageModItems("stage2", "buildcraftsilicon");
stageModItems("stage2", "buildcrafttransport");
stageModItems("stage2", "buildcraftrobotics");
stageModItems("stage2", "buildcraftfactory");
stageModItems("stage2", "buildcraftenergy");
stageModItems("stage2", "buildcraftbuilders");
stageModItems("stage2", "buildcraftcore");
stageModItems("stage2", "buildcraftlib");
stageModItems("stage2", "forestry");

//Stage 3
stageModItems("stage3", "harvestcraft");
stageModItems("stage3", "magneticraft");
stageModItems("stage3", "industrialrenewal");
stageModItems("stage3", "theoneprobe");
stageModItems("stage3", "openblocks");
stageModItems("stage3", "poweradapters");

//Stage 4
stageModItems("stage4", "immersiverailroading");
stageModItems("stage4", "immersivepetroleum");
stageModItems("stage4", "immersiveengineering");

//Stage 5
stageModItems("stage5", "ic2");
stageModItems("stage5", "techreborn");
stageModItems("stage5", "logisticspipes");
stageModItems("stage5", "rsgauges");
stageModItems("stage5", "translocators");
stageModItems("stage5", "worldcontrol");
stageModItems("stage5", "wrcbe");

//Stage 6
stageModItems("stage6", "rftools");
stageModItems("stage6", "portalgun");
stageModItems("stage6", "openmodularturrets");
stageModItems("stage6", "powersuits");
stageModItems("stage6", "galacticraftcore");
stageModItems("stage6", "galacticraftplanets");
stageModItems("stage6", "computercraft");

//Stage 7 Magic
stageModItems("stage7", "thaumcraft");
//stageModItems("stage7", "");
//stageModItems("stage7", "");

//Stage 8 Avaritia
stageModItems("stage8", "avaritia");

// Locks all items from a mod to a stage
stageModItems("stagedisabled", "mowziesmobs");

**Comment by darkhax** [comment]
Can you provide full logs?

**Comment by TheQuantumGeneral** [comment]
[latest.log](https://github.com/Darkhax-Minecraft/ItemStages/files/2498658/latest.log)

**Comment by TheQuantumGeneral** [comment]
I'll have to go back to try it but its working flawlessly now after a refactor

I only removed these mods

stageModItems("stage1", "forgemultipartcbe");
stageModItems("stage1", "microblockcbe");
stageModItems("stage1", "minecraftmultipartcbe");
stageModItems("stage1", "jaopca");
stageModItems("stage1", "mcmultipart");

// Locks all items from a mod to a stage
stageModItems("stagedisabled", "mowziesmobs");

stageModItems("stage2", "buildcraftcompat");
stageModItems("stage2", "buildcraftsilicon");
stageModItems("stage2", "buildcraftrobotics");
stageModItems("stage2", "buildcraftfactory");
stageModItems("stage2", "buildcraftenergy");
stageModItems("stage2", "buildcraftbuilders");
stageModItems("stage2", "buildcraftlib");

**Comment by darkhax** [comment]
If you work it out let me know. I believe the issue was caused by a crash in my mod from an unexpected input. So if that is the case I would like to fix it.
