### ISSUE TITLE
changeRestrictionTooltip No Longer Working

### ISSUE THREAD

**Issue by NillerMedDild** [Darkhax-Minecraft/ItemStages#34]
Hey o/ 
Tooltips are no longer modified in any way when staged with `mods.ItemStages.addItemStage(stage, item);`. Is that intended?
`changeRestrictionTooltip` is set to true.

**Comment by darkhax** [comment]
No, this is not intended. It is an issue with the code.

**Comment by darkhax** [comment]
This should be fixed in ItemStages 2.0.40. This release has some other experimental changes, but should be fine to use.

**Comment by NillerMedDild** [comment]
Lovely, thanks.
