### ISSUE TITLE
ItemStages on server has issues with items that have multiple right click functions

### ISSUE THREAD

**Issue by PhoenixMage** [Darkhax-Minecraft/ItemStages#35]
Running Modern Skyblock 3 Departed Modpack 3.5

Description of the problem including expected versus actual behavior:
When rightclicking the PSD anywhere, no manual shows.
When rightclicking the PSD onto a machine block, two dimension travels happen, one to go in, the next instantly to go out.
When rightclicking the Engineer's Manual anywhere, no manual shows.
All these behaviours don't happen in Creative mode (/gamemode 1)
Opping player has no effect.

Steps to reproduce:
Install the Modern Skyblock 3 pack locally (allocate at least 6GB of ram...).
Download and run the Modern Skyblock 3 server locally (allocate at least 3GB of ram...)
Log into server, run commands (op yourself on server):
/island create 1
/give yourname dirt 1
/give yourname sapling 1
Rightclick quest book (should be in inventory), select "Kitchensink Mode" and claim the quest reward (this unlocks everything)
/give yourname compactmachines3:psd
/give yourname compactmachines3:machine
Go into machine using PSD.
Observe a loading screen and then appearing right back in dimension 0.
/give yourname immersiveengineering:tool 1 3
Right click while holding manual and nothing occurs.

If you edsit the stages.zs script on both client and server and comment out line 830 "mods.ItemStages.addItemStage("up", <compactmachines3:psd>);" and line 811 "mods.ItemStages.addItemStage("hm", <immersiveengineering:tool:*>);" it resolves both these issues.

**Comment by darkhax** [comment]
This issue has been confirmed fixed with latest ItemStages and GameStages.
