### ISSUE TITLE
Can still equip armour from locked staged mods

### ISSUE THREAD

**Issue by TheQuantumGeneral** [Darkhax-Minecraft/ItemStages#37]
A lot of my players are reporting that zombies are dropping Nano armour from IC2. And they are able to equip it (just not hold it in their hotbar

Also you are able to carry restricted items in your inventory as long as you don't hold them in your hand

**Comment by artdude543** [comment]
- Carrying in your inventory will alway be a thing as far as I'm aware. As you'll end up having loads of items on the floor and it makes no sense to do it that way. Then you'll have lag issues in the world etc... also well designed modpacks would account for this to prevent items showing/dropping at various stages.
  - I.E. With SevTech we have mob stages and hide structures etc... but it takes a lot of work to do and custom mods to be used.
- Equping I can see as an issue and not at the same time. It's a "meh" thing to be honest. The mod could add support and I'll be down for that. But a good modpack would also account for this. But on servers it's harder to control. (But not impossible)

@darkhax I could look into adding support for preventing usage on the armour equiping if you feel this is valid for the mod?

**Comment by darkhax** [comment]
Detecting items in the inventory isn't a technical issue, the main reason against it would be that would be all over the floor. I will mark that as a potential feature request. Armor slots are already supported, so I am guessing the feature broke during an update, or another mod broke it.

**Comment by artdude543** [comment]
Hmm, I've never tested that feature in SevTech tbh I can check shortly. Unless your on the case. But from our expereicnce I don't feel like preventing people from having it in their inventoy is a bad thing. It's better than all over the floor, in one way it's nice so the players are able to collect but unable to use (if a tool/weapon etc..) as recipes would be staged they can't get around cheating items from friends cos they won't be able to craft said thing.

**Comment by TheQuantumGeneral** [comment]
Yeah the armour config is definately set to not allow armour but we can still wear it

https://github.com/TheQuantumGeneral/Quaesitum/blob/master/config/itemstages.cfg

Also yeah Itd be nice having a config setting for force dropping Items from the inventory so friends can't share things that work in the inventory (batteries/Auto feeders/item magnets) etc

**Comment by TheQuantumGeneral** [comment]
Yeah If nothing else though it'd be a nice little safety catch for a well designed mod pack. I've gone to a lot of effort in my mod pack Quaesitum with item stages, mob stages and game stages to ensure nothing is attainable before you're on the correct stage but players sharing our the occasional mistake could necessitate such a config.

If there's a situation where there's enough items dropping to cause an issue. That's on the pack maker

**Comment by darkhax** [comment]
After testing the main issue of being able to equip armor, this feature seems to be working correctly. In my test I used this script `mods.ItemStages.addItemStage("one", <minecraft:iron_chestplate>);`. I put the item on the ground, picked it up into a non-selected slot, opened my inventory and put the item in the armor slot. The item was immediately dropped onto the ground as expected. Please note that this test must not be performed in creative mod, as creative mode intentionally bypasses the checks in this mod for testing purposes.

**Comment by TheQuantumGeneral** [comment]
Okay. I figured it out. At least for ic2 armour it's not accounting the charge state.

Players were getting uncharged nano and quantum armour from mob drops. Which they could wear. But once they charged them to full they were restricted by staging

**Comment by darkhax** [comment]
I am going to close this as the root issue does not seem to be an actual issue. Tools and armors have different states which require special handling, that's just how they are. You can open up feature requests for the other stuff, but I will get to them eventually anyhow.
