### ISSUE TITLE
staged items are not hidden consistently in JEI

### ISSUE THREAD

**Issue by xkforce** [Darkhax-Minecraft/ItemStages#39]
Items that are in a stage that the player does not have access to are not hidden in JEI unless the hide ingredients option in JEI is toggled. i.e. hide ingredients off => on => off which doesn't survive a reboot of the game.

**Comment by darkhax** [comment]
I don't get what you're saying. This mod works out of the box with JEI, no config options need to be changed. Unless something has changed in newer versions of JEI.

**Comment by xkforce** [comment]
There was something weird going on between JEI, item stages and some other mod that was causing certain staged items to only be hidden if JEI's hide ingredients config was toggled back and forth.  It was also doing weird things with forestry in general which is why I'm closing this issue.

**Comment by darkhax** [comment]
I just updated to the latest JEI and cleaned out my config and it seems fine, so I am going to confirm that this is fixed.
