### ISSUE TITLE
[Feature?] Block Player Interaction if missing stage

### ISSUE THREAD

**Issue by clubpetey** [Darkhax-Minecraft/ItemStages#41]
Today, If I do this:

`mods.ItemStages.addItemStage("one", <minecraft:furnace>);`

While I cannot place a furnace in the world, I can still right click one that has been placed in the world and interact with it.  I'd like to block interacting with blocks in the world that the player does not have access to.

Brewing stand is a good example.  Even if I have stage-blocked all potions and ingredients, a player can still brew a potion with a brewing stand that happens to exist in the world (A few mods generate dungeons with them in the world).

**Comment by darkhax** [comment]
In the case of blocks in the world, there is no reliable way to tie the item back to the block. I would suggest looking into Ore Stages, which despite the name, will allow you to make the furnace and brewing stand look like other blocks, and prevent interacting with them.
