### ISSUE TITLE
Enchanting Books not hidden in JEI when staged

### ISSUE THREAD

**Issue by justinrusso** [Darkhax-Minecraft/ItemStages#42]
When staging enchantment books, the books end up staged but continue to show in JEI even with all stages cleared.

With a JEI update, the book returned from JEI changed slightly from
```
<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 0 as short}]})
```
to
```
<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 0}]})
```

Changing the script to the new nbt tag made the books staged (the tooltips states to the player it requires the stage set, and the name is "Unknown Item" but they still show in JEI.

Previous JEI: 4.13.1.223
New JEI: 4.14.4.264
ItemStages: 2.0.46

**Comment by darkhax** [comment]
Looking at the JEI issue report, it looks like Mezz added a hack related to books which caused this issue. I am going to defer this issue to him for now.
