### ISSUE TITLE
Item stages not working correctly with .withTag (or possibly just with Mekanism)

### ISSUE THREAD

**Issue by Golrith** [Darkhax-Minecraft/ItemStages#43]
When assigning stages to items that use the .withTag but the same ID+Meta, the .withTag appears to be ignored. I've noticed this behavior on Mekanism items.

For example, Mekanism cables:
`mods.ItemStages.addItemStage("L002", <mekanism:transmitter:1>.withTag({tier: 0}));
mods.ItemStages.addItemStage("XXMek", <mekanism:transmitter:1>.withTag({tier: 3}));`

The tier 0 item is getting assigned the XXMek stage too,

I'm also using a mod called TechGuns that makes use of .withTag but I've not seen any issues there. So it seems like there's some weird interaction between Mekanism and Item Stages.

**Comment by Golrith** [comment]
Having done some more investigation the solar panel issue is my error and has been resolved.

But, with different Item Stages set on the various mekanism:transmitter using the withtag tiering causes the tags to "cycle" every game load. Normally the with tag gives info such as contents, ammo level, etc, etc, but Mekanism is using it to define totally different items which I believe ItemStages does not account for as that's not the expected usage.

**Comment by darkhax** [comment]
ItemStages definitely does work for multiple variants of the same item. The issue is that you need to define the NBT tag correctly for it to work. Here is an example of how you can hide two variants of the potion item separately. 

```
mods.ItemStages.addItemStage("one", <minecraft:potion>.withTag({Potion: "minecraft:strong_harming"}));
mods.ItemStages.addItemStage("two", <minecraft:potion>.withTag({Potion: "minecraft:strong_healing"}));
```

NBT in ItemStages will also match partial NBT tags. For example this one will hide all level 5 enchantment books.

**Comment by Golrith** [comment]
That's the weird thing. I've got lots of .withTags items staged just fine, but on the Mekanism Transmitter items every time the game is reloaded, the stage moves between items.

I'm creatively spawning the item in, and then using /ct hand to get the item ID + tag which seems to be getting everything fine.

Let me triple check everything again in my scripts (I'm doing a research tree with questbook and item stages, so as you can imagine, it's quite big!)
