### ISSUE TITLE
Thermal Expansion machines are not staged properly

### ISSUE THREAD

**Issue by Frinn38** [Darkhax-Minecraft/ItemStages#45]
Well I want to stage differents machines of thermal expansion at differents stages but when I do : 
ItemStages.addItemStage("thermal1", <thermalexpansion:machine:0>);  //Resdstone furnace

The Redstone furnace is staged to "thermal1" but Compactor, Magma Crucible, Energetic Infuser, Sequential Fabricator, Alchemical Imbuer, Arcane Ensorcellator, Glacial Precipitator and Igneous Extruder get staged to "thermal1" too. Those machines have same ID (thermalexpansion:machine) but differents meta.
After some researches I found that all the machines that get the stage have the same nbt, don't know I this is linked to this issue.

When I stage the machines recipes with Recipes Stages this works correctly and only stage recipes for the redstone furnace, that's why I think it's an issue with Item Stages.

**Comment by darkhax** [comment]
This issue was fixed by an issue in the order of operations logic, and affected items with the same item and NBT but different metas. I've tested using the example you gave and it seems to be working with this. New update will be on curse in a few. 

```
mods.ItemStages.addItemStage("thermal1", <thermalexpansion:machine:0>);
```
