### ISSUE TITLE
[Enhancement]: Create a Config-Option or Change how ItemStages logs mods being staged.

### ISSUE THREAD

**Issue by Lanse505** [Darkhax-Minecraft/ItemStages#46]
Realistically when doing whole mod staging ItemStages should only log: 
"Adding item stage X to mod Y".

You don't have to log every item being applied to every item in that mod.
Stage > Item logging should probably be limited to the methods that actually takes an IItemstack/IIngredient component.

**_Why do you ask?_**

To avoid log spam,  how much log spam?
What about 14k when staging most of a 100 count mod pack :P
https://gist.github.com/Lanse505/c029ff729b6e7888e953db0e1c276dfd

Most of those 14k lines could realistically, in this case, be condensed into something like 57 lines of logging.

This would help greatly to condense the crafttweaker.log into fewer lines and makes it a lot easier to look through :)

**Comment by Darkhax** [comment]
Jared mentioned to me that CraftTweaker has logger level support although it doesn't seem to be fully implemented. New versions are also not so verbose with this info.
