### ISSUE TITLE
[Enhancement]: When staging liquids, make it stage the appropriate buckets for the liquids as well.

### ISSUE THREAD

**Issue by Lanse505** [Darkhax-Minecraft/ItemStages#47]
When staging liquids, it'd be useful to make it stage the appropriate buckets for the liquids as well.
This means I wouldn't have to stage both the liquids and the buckets separately :)

**Comment by darkhax** [comment]
```zs
mods.ItemStages.stageLiquidAndBucket("one", <liquid:water>);
```
