### ISSUE TITLE
Option to remove an item from a stage

### ISSUE THREAD

**Issue by Winddbourne** [Darkhax-Minecraft/ItemStages#48]
I've got some mods were I want to add pretty much everything to a single stage. But there are one or two items that I'd like to leave open.

For example, I'd like ancient warfare to be a single stage, but I want players to be able to make the fire pit and totem pole from its structures module . . . and just those two items.  They are very theme oriented towards a different line of stages entirely. 

Right now it looks like I'd have to add each item I want to block individually just to leave these things out . . . rather than adding the entire mod "ancient warfare" and then removing two or three items from the list. 

I'm hoping this is already a feature and just not shown in the wiki or on the project page; but if it's not please add it. :)

**Comment by darkhax** [comment]
Thanks for the request. This does already exist, it's `mods.ItemStages.removeItemStage`.
