### ISSUE TITLE
[feature request] Ability to change the restricted tool tip

### ISSUE THREAD

**Issue by Winddbourne** [Darkhax-Minecraft/ItemStages#49]
I'd like to change the tooltip "you do not know how to use this yet" to something else that fits my pack better. Unfortunately, I can't seem to find a way to alter it in the configuration files or on the WIKI. 

I'm using stages to restrict entire sets of mods into what amounts to player classes.  If you haven't chosen the right class option you won't be able to use an entire large mod such as Blood Magic or Immersive Engineering. 

If you find something that is restricted there is a good chance you aren't eventually going to learn how to use it. So I'd rather give the player a different message that works with the lore and progression of my pack.

**Comment by Darkhax** [comment]
You can use things like ResourceLoader and CraftTweaker to override translatable strings. All translation keys can be found [here](https://github.com/Darkhax-Minecraft/ItemStages/blob/master/src/main/resources/assets/itemstages/lang/en_US.lang).
