### ISSUE TITLE
[Bug] Items added to JEI cannot be hidden.

### ISSUE THREAD

**Issue by UnlimatedStone9** [Darkhax-Minecraft/ItemStages#52]
I've used CraftTweaker to show a specific item in JEI, then set its stage, for some reason the item does not get hidden by ItemStages in JEI thereafter.

Adding the item to JEI was done above the item stages script too, as follows:

mods.jei.JEI.addItem(<horsepower:chopping_block>.withTag({textureBlock: {id: "tfc:wood/log/kapok", Count: 1 as byte, Damage: 0 as short}}));

mods.ItemStages.addItemStage("craftingachoppingblock_kapok_log", <horsepower:chopping_block>.withTag({textureBlock: {id: "tfc:wood/log/kapok", Count: 1 as byte, Damage: 0 as short}}));

**Comment by UnlimatedStone9** [comment]
Hm, I noticed the item doesn't get dropped either, perhaps I've done something wrong.

**Comment by Darkhax** [comment]
If the item is not dropping it means your NBT is not valid to match that item. Some items will have different NBT on the client or server. The mod includes a test for verifying NBT works, for example 
```
mods.ItemStages.addItemStage("one", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short}]}));
```
So the NBT feature is working as intended.
