### ISSUE TITLE
Lock items using NBT wildcard.

### ISSUE THREAD

**Issue by friendlyhj** [Darkhax-Minecraft/ItemStages#55]
![Qxtm6A.jpg](https://s2.ax1x.com/2019/12/22/Qxtm6A.jpg)

To make effect clearer, I used [Hardcore Item Stages](https://www.curseforge.com/minecraft/mc-mods/hardcore-item-stages).

**Comment by friendlyhj** [comment]
Maybe This can work.
```
mods.ItemStages.addItemStage("alpha", <minecraft:iron_ingot>);
mods.ItemStages.addItemStage("alpha", <minecraft:iron_ingot>.withTag({RepairCost : 0}));
```

But as #50 said, we should be able to lock item with **any** NBT, instead of only matching the empty NBT.

**Comment by dong031001** [comment]
Seconded.

**Comment by Darkhax** [comment]
Closing as this is a duplicate of #50
