### ISSUE TITLE
Suggestion: scan players' inventories and throw locked items away

### ISSUE THREAD

**Issue by RisingInIris2017** [Darkhax-Minecraft/ItemStages#57]
Now ItemStage is only checking items which are held by players.
But for armors like chestplates, leggings, or rings and necklaces added by [Baubles Mod](https://github.com/Azanor/Baubles), They can be used without being held in hand.
I hope there could be a more effective or "aggressive" way to lock items with ItemStage Mod,
for example, ItemStage scans players' inventories every several ticks, and throw all of locked items onto ground. 
Maybe this is better than which ItemStage can do now.
This is my suggestion. If you have different opinions, please tell me.
Look forward to your reply!
Thanks in advance!

**Comment by Darkhax** [comment]
The reason this is not possible is to prevent griefing on servers. Imagine you are looking in your friends chest and pick up a weird item. If you could not have that item in your inventory you would not be able to give it back to them. The mod will already look through equipment slots and the offhand slot to prevent holding them there.
