### ISSUE TITLE
[Feature Request] Config option for disabling Logging Debug Data

### ISSUE THREAD

**Issue by juraj-hrivnak** [Darkhax-Minecraft/ItemStages#58]
This will help from the spam of these things
`[Client thread/INFO] [Item Stages]: Finished JEI Sync, took 0ms. 0 hidden, 0 shown.`
when gamestages are changing more rapidly

**Comment by Darkhax** [comment]
The logger for the game already has config options to configure this stuff. This system isn't very well documented but you can find non-mc examples by looking into Log4J. There are also several mods that can create custom logging filters.
