### ISSUE TITLE
Can't add items with items to stage

### ISSUE THREAD

**Issue by Enot1laz** [Darkhax-Minecraft/ItemStages#59]
Hi, I trying to add all mod (forestry) to stage with one method. And all OK, but some items(like bees, butterflies, saplings) with different but similar MBT don't want to add using this method. What I must do?

**Comment by Darkhax** [comment]
Generally you would use a * as the metadata to define a wildcard for all sub-items. Some items with complex NBT will require stages to be applied on a more specific basis. 

```
// All lvl 5 enchantments
mods.ItemStages.addItemStage("one", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short}]}));

// All enchanted books
mods.ItemStages.addItemStage("one", <minecraft:enchanted_book:*>);
```
