### ISSUE TITLE
Items handled oddly when having more than one stage

### ISSUE THREAD

**Issue by justinrusso** [Darkhax-Minecraft/ItemStages#6]
If an item is staged in two stages, and the player has one of the two, the item shows in JEI but still is restricted to the player.

Ideally, if the player has any stage of the stages an item has, they can see the item in JEI (which it does) as well as not being restricted to the player. I could see uses for the opposite - making it so the item is hidden and restricted until the player has all stages it has - possibly a way to give the modpack developer an option to specify which way to handle it?

**Comment by darkhax** [comment]
This behavior is likely to have changed with some of the recent updates. The mod currently allows for only one stage per item and if you try to add additional stages they will overwrite the old one. This is a very recent change. I do plan to restructure the code to explicitly allow this soon.

**Comment by darkhax** [comment]
Is this still an issue with newer versions?

**Comment by wootaboot** [comment]
yes, ive staged actually addition items to 2 stages however some stick with the mod stage and some go with the specific stage given to them, cant find a pattern on how to know which will have which stage.
