### ISSUE TITLE
Is there somewhere I can get help with learning this stuff

### ISSUE THREAD

**Issue by deftesthawk** [Darkhax-Minecraft/ItemStages#62]
I've watched some videos and looked at the 1.12 guide page as I can't find one for 1.16, but I can't seem to get my code to work.
I keep getting this error:
script.zs:1:0 script.zs:1:0: Cannot evaluate a package as expression

This is what I've got in my script file:
`mods.ItemStages.addItemStage("Copper_age", <item:minecraft:oak_planks>);`

This is just a test script to learn how to do it, but I can't seem to get it to work. I've even compared it to some mod packs to see if there's anything I did different/wrong it all looks the same to me

**Comment by deftesthawk** [comment]
The greater than and less than part in the code doesn't seem to show but in my comment above but just to confirm it is there

**Comment by Darkhax** [comment]
The 1.12 documentation is completely outdated. The 1.16.5 version is still an early preview so documentation for it has not been added to the Wiki or CraftTweaker docs yet. There are some example scripts that can be found [here](https://www.curseforge.com/minecraft/mc-mods/item-stages/files/3431085).
