### ISSUE TITLE
Itemstage unfamilar item

### ISSUE THREAD

**Issue by SumiBB** [Darkhax-Minecraft/ItemStages#76]
its not a real issue but it be cool to choose if u want to have the item to be called unfamiliar item or just the normal name unless there is a way to do it already
![2022-01-18_17 33 06](https://user-images.githubusercontent.com/97993186/150031540-f072c396-2d1b-47aa-a9e9-a6d41fe0154e.png)

**Comment by Darkhax** [comment]
This is already an option. https://docs.blamejared.com/1.16/en/mods/ItemStages/ItemStages#changing-restricted-name
