### ISSUE TITLE
Recipes and Items in JEI Hidden Stages Shown When using "U" Key

### ISSUE THREAD

**Issue by HenryMaxler** [Darkhax-Minecraft/ItemStages#79]
By pressing "U" on the crafting materials of Hidden Items, shows them in JEI along with everything else that can be crafted.  I thought if it was to be hidden in JEI they would not show up.

**Comment by Darkhax** [comment]
This appears to be an issue with JEI itself. The issue can be replicated by hiding the items manually without ItemStages. 
![image](https://user-images.githubusercontent.com/2250798/158923218-a79cea98-e548-4f49-b6ef-45808d465a88.png)
