### ISSUE TITLE
Staged items dropped from inventory after player is given a stage

### ISSUE THREAD

**Issue by darkphan** [Darkhax-Minecraft/ItemStages#8]
Version: 1.0.21

When a player gets a stage, the items from the stage are still thrown from their hand as if they do not have the stage. This does not happen with 1.0.20

**Comment by darkhax** [comment]
Thanks for the report, this was accidentally introduced in a performance improvement I made for world load times. Pushing a fix now.

**Comment by justinrusso** [comment]
Seems to have been fixed. Thanks 👍
