### ISSUE TITLE
Allowing Pickup by Tag Not Functioning (1.16.5)

### ISSUE THREAD

**Issue by Squeetsquib** [Darkhax-Minecraft/ItemStages#80]
ItemStages.restrict(<tag:items:forge:paladin>, "paladin").preventPickup(false);

This string does not seem to work, gating an item behind the tag "paladin" does not allow pickup of said item.

example: <tag:items:forge:paladin>.add(<item:minecraft:iron_sword>);

(no errors in syntax, not an enchanted item, script is saved as zs, tried with / without other mods). (ItemStages-Forge-1.16.5-3.0.9 and GameStages-Forge-1.16.5-7.3.13) Tried this with other non-vanilla items as well and no luck.

**Comment by Squeetsquib** [comment]
I'm guessing this is out of development and not to expect a response?

**Comment by Darkhax** [comment]
This feature has been tested and is working as intended. The examples you have written here have an invalid tag syntax. You can find a working example [here](https://github.com/Darkhax-Minecraft/ItemStages/blob/forge-1.16.5/src/main/resources/data/gamestages/scripts/itemstages/1_creating_restrictions.zs#L19).

Please note that tags are not synced to the client. This means that client-specific features such as tooltip changes will not be applied to tag based restrictions on a dedicated server. This is a vanilla limitation and is outside the scope of this mod.
