### ISSUE TITLE
Staged items with NBT Data doesn't get hidden in JEI. 1.12.2

### ISSUE THREAD

**Issue by MrGhostero** [Darkhax-Minecraft/ItemStages#83]
Hello,
I have a problem when I staged items with NBT Data it was not being hidden in JEI, but items that didn't have NBT Data did get hidden.

![Without Stage](https://user-images.githubusercontent.com/106885568/172022460-89ae5820-59c5-4f07-abf9-83e4b356ef9a.png)
![With Stage](https://user-images.githubusercontent.com/106885568/172022462-badcd13d-d5bd-4637-80a6-25cc9b04bc03.png)

**Comment by Darkhax** [comment]
Hello, 1.12.2 is no longer being supported.

When staging an item with NBT make sure JEI can be very picky. It needs the NBT to 100% match the NBT of the item being displayed. You can usually shortcut this by using the item stack wildcard however that is not guaranteed to work.
