### ISSUE TITLE
Incompatible with FTB Quests?

### ISSUE THREAD

**Issue by TemplarLouai** [Darkhax-Minecraft/ItemStages#85]
Hello! I hope you are doing great!

I have noticed an issue with the "ItemStages-Forge-1.19.2-5.0.2" version of the mod  
I understand it is still "alpha", I just wanted to report the issue!

The game launches fine with the mod, but I have noticed that if you have FTB Quests installed, and you try to open the quest book, a popup shows up on the top right saying "Error! Server doesn't have FTB quests"

With the mod removed from the mods folder, the quest book is accessible.

**Comment by Darkhax** [comment]
This sounds like an error with FTB Quests. This mod has no official support or integration with FTB Quests.
