### ISSUE TITLE
Remove Item Stage for OreDict

### ISSUE THREAD

**Issue by Susul-1312** [Darkhax-Minecraft/ItemStages#87]
You are able to add Items to stages by their OreDict entry, but the inverse would also be extremely useful.
Potential usecase: You want to restrict mods to stages, but you want an ore shared by multiple mods to be completely unrestrictred.

This would also make the mod more predictable, as `addItemStage` allows you to use OreDicts, but if you do the same with `removeItemStage` you get an error

**Comment by Darkhax** [comment]
This is already something you can do using CraftTweaker's scripting language by just looping through the tag you want to remove stages from. If you need more help with your scripts try joining the [CraftTweaker discord](https://discord.blamejared.com).
