### ISSUE TITLE
[Request]Light restriction option

### ISSUE THREAD

**Issue by thephoenixlodge** [Darkhax-Minecraft/ItemStages#9]
With my pack being exploration oriented, forcing the player to drop an item they aren't allowed to use yet if they happen to find it is a bit heavy handed. As such I would like the option to still prevent the player from using the item, but also still be able to carry it and see its name.

**Comment by darkhax** [comment]
Hi, thanks for reminding me about your request. I will try to add this tonight for you.

**Comment by darkhax** [comment]
This has been added as a config option in the latest release.
