### ISSUE TITLE
[1.19.2] Can't pick up a staged item (furnace) even though I have the stage

### ISSUE THREAD

**Issue by vizthex123** [Darkhax-Minecraft/ItemStages#91]
It's very odd, as other items work fine.

Screenshots of me having the stage and the item being staged with CraftTweaker:
![image](https://github.com/Darkhax-Minecraft/ItemStages/assets/31721920/62610a5f-2876-4758-bef2-f05346bda072)
![image](https://github.com/Darkhax-Minecraft/ItemStages/assets/31721920/770cd8cc-f2f4-4fff-9e70-76b5c035cf33)

Log:
[latest.log](https://github.com/Darkhax-Minecraft/ItemStages/files/12776565/latest.log)

Not sure if it'll help, but here's the CraftTweaker log too:
[crafttweaker.log](https://github.com/Darkhax-Minecraft/ItemStages/files/12776566/crafttweaker.log)

(also, there should be a colon after the "following stages" text instead of a period. Slightly bothers me that there isn't).

**Comment by Darkhax** [comment]
Hi, I have tried this with the information you have provided and everything seems to be working as intended. It's possible the furnace is not the item you think it is or you have staged it with multiple restrictions. You can use F3 + H and look at the tooltip of the furnace in creative mode for more info. The tooltip will only show one restriction at a time so you will likely need to add the stage it displays and looks again.

**Comment by vizthex123** [comment]
> Hi, I have tried this with the information you have provided and everything seems to be working as intended. It's possible the furnace is not the item you think it is or you have staged it with multiple restrictions. You can use F3 + H and look at the tooltip of the furnace in creative mode for more info. The tooltip will only show one restriction at a time so you will likely need to add the stage it displays and looks again.

yeah, i think it was either that or a file got kinda borked and i had to reinstall the mod. Managed to fix it though. I'll close this since it's kind of a non-issue.
