### ISSUE TITLE
Cannot evaluate a package as expression

### ISSUE THREAD

**Issue by DarkTerraYT** [Darkhax-Minecraft/ItemStages#92]
I have two .zs scripts, one called stagePROJECTE.zs and stagePROJECTEXPANSION.zs

the two contents of these files are

stagePROJECTEXPANSION.zs:
mods.ItemStages.stageModItems("projectExpansion", "projectexpansion");

and for stagePROJECTE.zs:
mods.ItemStages.stageModItems("stageProjecte", "projecte");

**Comment by Darkhax** [comment]
The script you have written is for Minecraft 1.12.2 but I am guessing you're using a newer version? For Minecraft 1.16.5 and up you should use this [documentation](https://docs.blamejared.com/1.16/en/mods/ItemStages/ItemStages).

**Comment by DarkTerraYT** [comment]
Ah, thank you. I looked in 1.19 but couldn't find anything for it, should've looked harder 😅. You should probably update that or at least put something somewhere that says that the script example is for 1.12.2
